# Generated by Django 5.0.2 on 2024-02-22 23:23

import django.db.models.deletion
import django_resized.forms
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=50, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Autores',
                'verbose_name_plural': 'Autores',
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='EstadoArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estados de Articulos',
                'verbose_name_plural': 'Estados de Articulos',
                'db_table': 'EstadoArticulos',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=360, null=True, verbose_name='Descripcion SEO')),
                ('tags', models.CharField(max_length=400, null=True, verbose_name='TAGS')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('contenido', tinymce.models.HTMLField(max_length=30000, verbose_name='Contenido')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('visitas', models.IntegerField(default=0, null=True, verbose_name='Total Visitas')),
                ('likes', models.IntegerField(default=0, null=True, verbose_name='Likes')),
                ('ip_likes', models.CharField(default='Estuardo Ramírez', max_length=100, verbose_name='Like IP')),
                ('compartidos', models.IntegerField(default=0, null=True, verbose_name='Veces Compartidas')),
                ('prioridad', models.FloatField(default=0.9, verbose_name='Prioridad del sitio')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='images/', verbose_name='Imágen del artículo')),
                ('descripcion_imagen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Informacion de la imágen')),
                ('autor', models.ManyToManyField(to='Blog.autores', verbose_name='Autor')),
                ('categorias', models.ManyToManyField(to='Blog.categoria', verbose_name='Categorías')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.estadoarticulos', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'Articulo',
            },
        ),
    ]
