# Generated by Django 5.0.2 on 2024-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ip_likes',
            field=models.CharField(max_length=100, verbose_name='Like IP'),
        ),
    ]
