# Generated by Django 5.0.2 on 2024-03-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_articulo_ip_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='ip_likes',
        ),
    ]
