# Generated by Django 5.0.2 on 2024-02-22 23:23

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='images_portafolio/', verbose_name='Imágen')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=230, verbose_name='Descripción')),
                ('enlace', models.URLField(max_length=255, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Certificaciones',
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=60, unique=True, verbose_name='Dirección de correo')),
                ('subscribe_to_newsletter', models.BooleanField(default=False, verbose_name='Suscribirse al boletín')),
            ],
        ),
        migrations.CreateModel(
            name='EmailsEnviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=60, verbose_name='De')),
                ('_to', models.CharField(max_length=100, verbose_name='A')),
                ('_subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('_body', models.CharField(max_length=4000, verbose_name='Cuerpo')),
                ('_datetime', models.DateField(auto_now_add=True, verbose_name='Enviado el')),
            ],
            options={
                'verbose_name': 'Correos Enviados',
                'verbose_name_plural': 'Correos Enviados',
                'db_table': 'EmailsEnviados',
            },
        ),
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de la Persona')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo de la Persona')),
                ('mensaje', models.CharField(max_length=4000, verbose_name='Mensaje de la Persona')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('es_spam', models.BooleanField(blank=True, default=False, verbose_name='Spam')),
                ('terminos', models.BooleanField(default=False, verbose_name='Terminos')),
            ],
            options={
                'verbose_name': 'Formulario de Contacto',
                'verbose_name_plural': 'Formulario de Contactos',
                'db_table': 'formulariocontacto',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descHabilidad', models.CharField(max_length=100, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='IdentificadorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=40, verbose_name='Identificador')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Identificador de Email',
                'verbose_name_plural': 'Identificador de Emails',
                'db_table': 'IdentificadoresEmails',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='images_portafolio/', verbose_name='Imágen')),
                ('texto_largo', models.TextField(max_length=2000, verbose_name='Texto Largo')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolio',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=230, null=True, verbose_name='Descripción')),
                ('imagen', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='images_portafolio/', verbose_name='Imágen')),
                ('texto_enlace', models.CharField(max_length=50, null=True, verbose_name='Texto del Enlace')),
                ('enlace', models.URLField(max_length=255, null=True, verbose_name='Enlace')),
                ('alt_imagen', models.CharField(max_length=50, null=True, verbose_name='Alt Imagen')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
