# Generated by Django 5.0.2 on 2024-02-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
    ]
