name: Deploy-ASPNET-App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ingresa al servidor y ejecuta comandos
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /Servidor2024
            git pull origin master
            cd /Servidor2024/ServidorASP
            dotnet publish -c Release --no-warn:CSxxxx
            sudo systemctl restart my-web.service
            systemctl restart nginx.service
