name: Django Tests

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            NAME_DB: ${{ secrets.NAME_DB }}
            USER_DB: ${{ secrets.USER_DB }}
            PASS_DB: ${{ secrets.PASS_DB }}
            HOST_DB: ${{ secrets.HOST_DB }}
            PORT_DB: ${{ secrets.PORT_DB }}

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  cd ServidorDjango
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  cd ServidorDjango
                  python3 manage.py test